cohort_base:
  dataset: rl_project
  table: cohort_base

logging:
  path: validation.log
  patient_combination_path: patient_combinations.log
  train_path: train.log
  predict_path: predict.log
  tune_path: tune.log
  evaluate_path: evaluate.log

hugging_face:
  interim_data_repo: ADS599-Capstone/interim_data
  modeling_data_repo: ADS599-Capstone/modeling_data
  cohort:
    config_name: cohort_full
    split_name: cohort_base
    data_dir: cohort
  empty_patient_state:
    config_name: empty_patient_state
    split_name: empty_patient_state
    data_dir: patient_state
  dispensed_meds:
    config_name: dispensed_meds
    split_name: er_and_ward
    data_dir: dispensed_meds
  ecg:
    config_name: ecg_results
    split_name: full_ecg
    data_dir: ecg
  medrecon:
    config_name: medrecon
    split_name: medrecon_full
    data_dir: medrecon_data
  microbiology:
    config_name: microbiology
    split_name: microbiology_full
    data_dir: microbiology_data
  radiology:
    config_name: rad_results
    split_name: rad_full
    data_dir: rad_data
  omr_height:
    config_name: height
    split_name: height_full
    data_dir: height_data
  omr_weight:
    config_name: weight
    split_name: weight_full
    data_dir: weight_data
  labs:
    config_name: lab_results
    split_name: labs_full
    data_dir: labs
  triage_vitals:
    config_name: triage_vitals
    split_name: triage_vitals_full
    data_dir: triage_vitals_data
  full_patient_state:
    config_name: full_patient_state
    split_name: full_patient_state
    data_dir: full_patient_state

sql_dir: sql_scripts
artifacts_dir: artifacts

time_block: 30
