random_state: 10
model:
  input_size: 236 # can also get this dynamically during training
  hidden_size: 256
  num_layers: 2
  dropout: 0.2
  batch_first: True
  num_classes: 2

training:
  epochs: 5
  batch_size: 16
  learning_rate: 1e-4
  weight_decay: 0.1
  optimizer: adamw
  training_update: 500
  # Early Stopping Variables
  patience: 3
  tol: .001

data:
  pad_length: 100 # This is the max number of actions taken in a patients stay.  Over 3k records have more than 100
  stay_length: 100 # Drop any ed stays with length of stay (in days) greater than this.  About 9500 records were longer than 100 days
  scaling_cols:
    - anchor_age
    - acuity
    - current_temperature
    - current_heartrate
    - current_resprate
    - current_o2sat
    - current_sbp
    - current_dbp
    - current_pain
    - current_pulse_pressure
    - current_map
    - height
    - weight
  target_col: terminal_event
  stay_id_col: ed_stay_id
  step_col:
  train_size: 0.8
  batch_size: 16

artifacts:
  dir: modeling/artifacts/lstm
