random_state: 10
model:
  input_size: 236 # can also get this dynamically during training
  hidden_size: 256
  num_layers: 2
  dropout: 0.2
  batch_first: True
  num_classes: 2

training:
  epochs: 5
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.1
  optimizer: adamw
  training_update: 500
  # Early Stopping Variables
  patience: 3
  tol: .001

step_by_step:
  train_size: 0.6

data:
  pad_length: 100 # This is the max number of actions taken in a patients stay.  Over 3k records have more than 100
  stay_length: 100 # Drop any ed stays with length of stay (in days) greater than this.  About 9500 records were longer than 100 days
  target_col: terminal_event
  stay_id_col: ed_stay_id
  step_col:
  train_size: 0.8
  batch_size: 16

artifacts:
  dir: modeling/artifacts/lstm
  sbs_dir: modeling/artifacts/step_by_step
